version: 2.1

aliases:
  - &defaults
    docker:
      - image: sirhill/truffle
    parameters:
      package:
        type: string
        default: .
    working_directory:
      ~/project/<< parameters.package >>

  - &cache_key_node_modules
    key: node_modules-v1-{{ checksum "package-lock.json" }}

  - &matrix_workflow_job2
    matrix:
      parameters:
        package: ["common", "token", "oracle"]
    requires:
      - dependencies

  - &matrix_workflow_job
     package: common
     requires:
       - dependencies

jobs:
  dependencies:
    <<: *defaults
    steps:
      - run:
          command: pwd
      - checkout:
          path: ~/project
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: ~/project
          paths:
            - << parameters.package >>
  lint:
    <<: *defaults
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/project
      - run:
          name: Linter
          command: yarn run lint
  test:
    <<: *defaults
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/project
      - run:
          name: Unit tests
          command: yarn run test
  coverage:
    <<: *defaults
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/project
      - run:
          name: Unit tests with coverage report
          command: yarn run coverage
      - run:
          name: Upload coverage
          command: |
            bash <(curl -s https://codecov.io/bash) -F moduleA
workflows:
  workflow:
    jobs:
      - dependencies
      - lint:
          <<: *matrix_workflow_job
      - test:
          <<: *matrix_workflow_job
      - coverage:
          <<: *matrix_workflow_job
